services:

    #PHP Service
    php:
        build:
            context: ./php
            dockerfile: ./Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}_php
        working_dir: /var/www
        volumes:
            - ../:/var/www/app
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - net

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www/app
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - net

    #MySQL Service
    mysql:
        image: mysql:latest
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - net

volumes:
    mysql_data:
        name: ${COMPOSE_PROJECT_NAME}_mysql_data
        driver: local

networks:
    net:
        name: ${COMPOSE_PROJECT_NAME}_net
        driver: bridge
